name: sirs_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: 4.17.0
  cupertino_icons: ^1.0.6
  curved_labeled_navigation_bar: ^2.0.2
  curved_navigation_bar: ^1.0.3
  date_input_form_field: ^1.2.0
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_pagination: ^3.1.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get: 4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  panara_dialogs: ^0.1.4
  shimmer: ^3.0.0
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_lints: 3.0.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
    - assets/images/
  uses-material-design: true
